admincp_news_page:
    path:     /
    defaults: { _controller: AppBundle:Admin/AdminNews:index }

admincp_news_create_page:
    path:     /create
    defaults: { _controller: AppBundle:Admin/AdminNews:create }

admincp_news_edit_page:
    path:     /edit/{id}
    defaults: { _controller: AppBundle:Admin/AdminNews:edit }

admincp_news_delete_page:
    path:     /delete/{id}
    defaults: { _controller: AppBundle:Admin/AdminNews:delete }